# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # General file checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--unsafe]      # Allow custom YAML tags
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-docstring-first
  - id: debug-statements
  - id: name-tests-test
    args: [--pytest-test-first]

  # Python code formatting with ruff (replaces black, isort, flake8)
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
      # Run the linter
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
  - id: ruff-format

  # Type checking with mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
    - types-PyYAML
    args: [--ignore-missing-imports, --no-strict-optional]
    exclude: ^(tests/|notebooks/)

  # Security checks
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.0
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['bandit[toml]']
    exclude: ^tests/

  # Secrets detection
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.22.1
  hooks:
  - id: gitleaks

  # Markdown linting
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
  - id: markdownlint
    args: [--fix]

  # YAML formatting
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

  # Dockerfile linting
- repo: https://github.com/hadolint/hadolint
  rev: v2.13.1-beta
  hooks:
  - id: hadolint-docker
    args: [--ignore, DL3008, --ignore, DL3013, --no-color]
    files: Dockerfile$

# Configuration for pre-commit.ci (optional)
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [gitleaks]  # Skip gitleaks in CI (can be slow)
  submodules: false
