
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - ../../.env
    environment:
      - QDRANT_PORT=6333
      - QDRANT_GRPC_PORT=6334
      #- QDRANT_API_KEY=QDRANT_API_KEY
    restart: always
    networks:
      - qdrant-network

volumes:
  qdrant_storage:
    driver: local

networks:
  qdrant-network:
    driver: bridge