
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    env_file:
      - ../../.env
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
      #- QDRANT__SERVICE__API_KEY=9UQEpDHjOqv1B9FGDRelHCmW2iWGSGCr
    restart: always
    networks:
      - qdrant-network

volumes:
  qdrant_storage:
    driver: local

networks:
  qdrant-network:
    driver: bridge