name: Build & Publish Docker Image (processing)

on:
  workflow_dispatch:
  push:
    paths:
    - src/processing/Dockerfile
    - src/processing/pyproject.toml
    - src/processing/uv.lock
    - src/processing/.python-version
    - src/processing/extract_law_text.py

jobs:
  build-and-push-processing:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_IMAGE_NAME_PROCESSING: ${{ vars.DOCKER_IMAGE_NAME_PROCESSING }}
    steps:
    - id: checkout
      name: Checkout code
      uses: actions/checkout@v5

    - id: setup_buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: docker_login
      name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - id: date_tag
      name: Get date tag
      run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - id: build_and_push
      name: Build and push Docker image (latest)
      uses: docker/build-push-action@v6
      with:
        context: ./src/processing
        push: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:latest
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:${{ steps.date_tag.outputs.tag }}

    - id: output_details
      name: Output image details
      run: |
        echo "SUCCESS: Docker image built and pushed successfully!"
        echo "Image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:latest"
        echo "Image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:${{ steps.date_tag.outputs.tag }}"
        echo "You can now pull the image with:"
        echo "  docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:latest"
