name: Build & Publish Docker Image (API)

on:
  workflow_dispatch:
  push:
    paths:
    - src/lus_laboris_api/Dockerfile
    - src/lus_laboris_api/pyproject.toml
    - src/lus_laboris_api/uv.lock
    - src/lus_laboris_api/.python-version
    - src/lus_laboris_api/api/**

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_IMAGE_NAME_RAG_API: ${{ vars.DOCKER_IMAGE_NAME_RAG_API }}
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      id: setup_buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      id: docker_login
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_PASSWORD }}

    - name: Get date tag
      id: date_tag
      run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

    - name: Build and push Docker image (latest)
      id: build_and_push
      uses: docker/build-push-action@v6
      with:
        context: ./src/lus_laboris_api
        push: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_RAG_API }}:latest
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_RAG_API }}:${{ steps.date_tag.outputs.tag }}

    - name: Output image details
      id: output_details
      run: |
        echo "SUCCESS: Docker image built and pushed successfully!"
        echo "Image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_RAG_API }}:latest"
        echo "Image: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_RAG_API }}:${{ steps.date_tag.outputs.tag }}"
        echo "You can now pull the image with:"
        echo "  docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_RAG_API }}:latest"
