name: Build & Publish Docker Image (processing)

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/processing/Dockerfile'
      - 'src/processing/extract_law_text.py'
      - 'src/processing/pyproject.toml'
      - 'src/processing/.python-version'

jobs:
  build-and-push-processing:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      DOCKER_IMAGE_NAME_PROCESSING: ${{ vars.DOCKER_IMAGE_NAME_PROCESSING }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Get date tag
        id: date_tag
        run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (latest)
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          context: ./src/processing
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:latest
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME_PROCESSING }}:${{ steps.date_tag.outputs.tag }}
